config/routes.rb
Rails.application.routes.draw do
   

  get 'schedules/index'

  get 'prog/index'

  get 'schedule/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
        root to: 'home#index'
       
        get 'announcer', to: 'announcer#index', as: :announcer
        get 'contact', to: 'contact#index', as: :contact
        get 'about', to: 'about#index', as: :about 
        get 'prog', to: 'prog#index', as: :prog



        #album
        get "fotos", to: "albums#index", as: :albums
        get "fotos/:slug", to: "albums#show", as: :album
        
        #video
        get 'video', to: 'video#index', as: :video
        get "videos/:slug", to: "video#show", as: :videos

        #promotion
        get 'promotion', to: 'promotion#index', as: :promotion
        get "promotion/:slug", to: "promotion#show", as: :promotions
end







 # get 'gallery/index'

  # devise_for :users
  # mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  # root "home#index"

  # Album
#   get "fotos" => "albums#index", as: :albums
#   get "fotos/:slug" => "albums#show", as: :album

#   # Contact
#   get "contato" => "contacts#index", as: :contact
#   post "contato" => "contacts#create", as: :create_contact

#   # News
#   get "noticias" => "news#index", as: :news
#   get "noticias/:category" => "news#list_by_category", as: :news_by_category
#   get "noticias/:category/:slug" => "news#show", as: :news_show

#   # Routes Content_Builder
#   path_url = "admin/content_builder/:id/create_images"
#   path_method = "rails_admin_content_builder/content_builder#create_images"
#   put path_url => path_method
# end

app/views/layouts/content/_footer.html.erb
<!-- Footer -->
  <footer class="page-footer font-small blue-grey lighten-5">

    <div style="background-color: #21d192;">
      <div class="container">

        <!-- Grid row-->
        <div class="row py-4 d-flex align-items-center">

          <!-- Grid column -->
          <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
            <h6 class="mb-0">Get connected with us on social networks!</h6>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-6 col-lg-7 text-center text-md-right">

            <!-- Facebook -->
            <a class="fb-ic">
              <i class="fab fa-facebook-f white-text mr-4"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic">
              <i class="fab fa-twitter white-text mr-4"> </i>
            </a>
            <!-- Google +-->
            <a class="gplus-ic">
              <i class="fab fa-google-plus-g white-text mr-4"> </i>
            </a>
            <!--Linkedin -->
            <a class="li-ic">
              <i class="fab fa-linkedin-in white-text mr-4"> </i>
            </a>
            <!--Instagram-->
            <a class="ins-ic">
              <i class="fab fa-instagram white-text"> </i>
            </a>

          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row-->

      </div>
    </div>

    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">

      <!-- Grid row -->
      <div class="row mt-3 dark-grey-text">

        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

          <!-- Content -->
          <h6 class="text-uppercase font-weight-bold">Tropical FM </h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>A Rádio Tropical FM - Anaurilândia foi criada em 2010, somos uma rádio independente e gostamos de uma boa música, escute nossa playlist e participe das promoções, esperamos por vocês!</p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Novidades</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a class="dark-grey-text" href="promotion">Promoções</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Mais tocadas</a>
          </p>
          <p>
            <a class="dark-grey-text" href= <%= albums_path%>>Galeria de fotos</a>
          </p>
          <p>
            <a class="dark-grey-text" href="video">Galeria de vídeos</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">LINKS ÚTEIS</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a class="dark-grey-text" href="prog">Programação</a>
          </p>
          <p>
            <a class="dark-grey-text" href="announcer">Locutores</a>
          </p>
          <p>
            <a class="dark-grey-text" href="about">Sobre nós</a>
          </p>
          <p>
            <a class="dark-grey-text" href="contact">Contato</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">FAle conosco</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <i class="fas fa-home mr-3"></i>R.Uruguaiana, 1239, Anaurilândia-MS</p>
          <p>
            <i class="fas fa-envelope mr-3"></i> contato@tropicalfm.com</p>
          <p>
            <i class="fas fa-phone mr-3"></i> (67) 3441-3441</p>
          <p>
            <i class="fas fa-print mr-3"></i> (67) 9.9931-2105</p>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
      <div class="footer-copyright text-center py-3">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <div class="row justify-content-lg-between">
                <div class="col-12 col-lg-6">
                  <div class="d-flex justify-content-center justify-content-lg-start">
                    &copy; <%= Time.now.year %> - Todos os direitos reservados.
                  </div>
                </div>
                <div class="col-12 col-lg-6">
                  <div class="d-flex justify-content-center justify-content-lg-end">
                    Desenvolvido por:
                    <a class="ml-2" target="_blank" href="https://www.agenciaw3.digital/"
                    data-toggle="tooltip" title="Agência W3">
                      <%= image_tag "logo_w3.svg", alt: "Agência W3" %>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <!-- Copyright -->

  </footer>
<!-- Footer -->

app/views/layouts/content/_header.html.erb
<!--Navbar-->
     
  <nav class="navbar navbar-expand-lg navbar-dark green">

    <!-- Navbar brand -->
    <span class="text-white text-uppercase ml-1">Ouça ao vivo</span>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation"> 
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <li class="nav-item">
          <a class="text-white text-uppercase ml-1" href="https://play.google.com/store/apps/details?id=br.com.radiosapp5.tropicalfm879">Baixe nosso aplicativo</a>
    </li>
    
    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

      <!-- Links -->
        <li class="nav-item">
          <a class="text-white text-uppercase ml-1" href="contact">Fale conosco</a>
        </li>
      </ul>

      
    </div>
  </nav>
  
  <nav class="navbar navbar-expand-lg navbar-dark Dark">

    <!-- Navbar brand -->
    
    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    
        <div class="view">
            <%= image_tag 'logo.png', class: "d-block w-100" %>             
          <div class="mask rgba-black-light"></div>
        </div>         
      </div>       
    <div class="collapse navbar-collapse" id="basicExampleNav">
           <!-- Links -->
 <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="navbar-brand" href="/">Home</a>
            <span class="sr-only">(current)</span>
          </a>
        </li>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="about">SOBRE NÓS
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="prog">PROGRAMAÇÃO</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="promotion">PROMOÇÃO</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="announcer">LOCUTORES</a>
        </li>
        <%# <li class="nav-item">
          <a class="nav-link" href="#">CONTATO</a>
        </li> %>
        <!-- Dropdown -->
              
       <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Galerias</a>
          <div class="dropdown-menu dropdown-green" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href=<%= albums_path %>>Galeria de fotos</a>
            <a class="dropdown-item" href=<%= video_path %>>Galeria de vídeos</a>
             
          </div>
        </li>
      </ul>
          
      <!-- Links -->

      <%# <form class="form-inline ml-4">
        <div class="md-form my-0">
          <input class="form-control mr-sm-2 mask--phone" type="text" placeholder="Search" aria-label="Search">
        </div>
      </form> %>
    </div>
    <!-- Collapsible content -->

  </nav>
<!--/.Navbar-->

app/views/layouts/content/_scripts.html.erb
<!-- Scripts to MDB -->
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="/vendor/assets/js/jquery.min.js"></script>
  <script type="text/javascript" src="/vendor/assets/js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="/vendor/assets/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="/vendor/assets/js/mdb.min.js"></script>
  <!-- JQuery Mask -->
  <script type="text/javascript" src="/vendor/assets/js/jquery.mask.min.js"></script>
<!-- End Script -->