config/routes.rb
Rails.application.routes.draw do
   

  get 'schedules/index'

  get 'prog/index'

  get 'schedule/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
        root to: 'home#index'
       
        get 'announcer', to: 'announcer#index', as: :announcer
        get 'contact', to: 'contact#index', as: :contact
        get 'about', to: 'about#index', as: :about 
        get 'prog', to: 'prog#index', as: :prog



        #album
        get "fotos", to: "albums#index", as: :albums
        get "fotos/:slug", to: "albums#show", as: :album
        
        #video
        get 'video', to: 'video#index', as: :video
        get "videos/:slug", to: "video#show", as: :videos

        #promotion
        get 'promotion', to: 'promotion#index', as: :promotion
        get "promotion/:slug", to: "promotion#show", as: :promotions
end







 # get 'gallery/index'

  # devise_for :users
  # mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  # root "home#index"

  # Album
#   get "fotos" => "albums#index", as: :albums
#   get "fotos/:slug" => "albums#show", as: :album

#   # Contact
#   get "contato" => "contacts#index", as: :contact
#   post "contato" => "contacts#create", as: :create_contact

#   # News
#   get "noticias" => "news#index", as: :news
#   get "noticias/:category" => "news#list_by_category", as: :news_by_category
#   get "noticias/:category/:slug" => "news#show", as: :news_show

#   # Routes Content_Builder
#   path_url = "admin/content_builder/:id/create_images"
#   path_method = "rails_admin_content_builder/content_builder#create_images"
#   put path_url => path_method
# end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page_description = "Descrição Tropical FM"
    @page_keywords = ["Home", "Início", "Rails", "Tropical FM"]
    @slides = Slide.where(active: true)
    @top_hits = TopHit.where(active: true).order(:colocation)
    @promotions = Promotion.where(:status => true)
    .where('start_date <= ?', Time.now)
    .where('finish_date >= ?', Time.now).order("title asc").page(params[:page])

    @videos = Video.where("publish_date <= ?", Time.current)
    .where(status: true).order(publish_date: "DESC").page(params[:page]).per(3) 

     @albums = Album.where("publish_date <= ?", Time.current)
     .where(status: true).page(params[:page]).per(3)

     @albums = Album.all()

      @hits_mobile = TopHit.active_and_ordered
      @hits_desktop = @hits_mobile.each_slice(3)

     @schedules = Schedule.ordered_and_grouped
  end
end

app/views/home/content/_most_played.html.erb
<div class="row">
  <div class="col">
    <h5 >
      <i class="fab fa-itunes-note mr-2"></i>
       As Mais Tocadas na rádio
    </h5>

    <%= render "home/content/most_played_desktop" %>

    <%= render "home/content/most_played_mobile" %>
  </div>
</div>

app/views/home/content/_most_played_desktop.html.erb
 <div id="carousel-most-played-sm" class="carousel d-none d-sm-block slide carousel-multi-item carousel-multi-item-2" data-ride="carousel">
  <div class="carousel-inner carousel-most-played" role="listbox">
    <% if @hits_desktop.present? %>
      <% @hits_desktop.each_with_index do |hits, index|%>
        <div class="carousel-item <%= index === 0 ? 'active' : '' %>" > 
          <% hits.each do |hit| %>
            <div class="col col-md-4 mb-3">
              <div class="card">
                <iframe 
                  width="100%" height="100%" src="https://www.youtube.com/embed/<%= hit.code %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
                </iframe>
                <div class="w-100 most-played-legend green lighten-4 p-2">
                  <span class="icon-most-played">
                    <%= hit.colocation.to_i %>ª
                  </span>
                  <p class="most-played-title">
                    Mais Tocada
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="controls-top">
    <a class="black-text" href="#carousel-most-played-sm" data-slide="prev"><i class="fas fa-angle-left fa-3x pr-3"></i></a>
    <a class="black-text" href="#carousel-most-played-sm" data-slide="next"><i class="fas fa-angle-right fa-3x pl-3"></i></a>
  </div>
</div>

app/views/home/content/_most_played_mobile.html.erb
<div id="carousel-most-played-mob" class="carousel d-sm-none slide carousel-multi-item carousel-multi-item-2" data-ride="carousel">
  <div class="carousel-inner carousel-most-played" role="listbox">
    <% if @hits_mobile.present? %>
      <% @hits_mobile.each_with_index do |hit, index| %>
        <div class="carousel-item <%= index === 0 ? 'active' : '' %>">
          <div class="col mb-3">
            <div class="card">
              <iframe
                width="100%" height="100%" src="https://www.youtube.com/embed/<%= hit.code %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
              </iframe>
              <div class="w-100 most-played-legend green lighten-4 p-2">
                <span class="icon-most-played">
                  <%= hit.colocation.to_i %>ª 
                </span>
                <p class="most-played-title">
                  Mais Tocada
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="controls-top">
    <a class="black-text" href="#carousel-most-played-mob" data-slide="prev"><i class="fas fa-angle-left fa-3x pr-3"></i></a>
    <%# <%=raise%> 
    <a class="black-text" href="#carousel-most-played-mob" data-slide="next"><i class="fas fa-angle-right fa-3x pl-3"></i></a>
  </div>
</div>

app/views/home/content/_schedule.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center mb-5 flex-wrap button-wrapper">
      <% @schedules.each do |key, value| %>
        <button type="button" class="btn waves-effect filter"
        id="<%= key.parameterize[0..2] %>"
        data-rel="<%= key.parameterize[0..2] %>">
          <%= key %>
        </button>
      <% end %>
    </div>
  </div>

  <div class="gallery w-100 mx-auto d-flex flex-column flex-sm-row justify-content-sm-between flex-wrap mx-2" id="gallery">
    <% @schedules.each do |key, value| %>
      <% value.each do |schedule_item|%>
        <div class="mb-3 yellow lighten-4 pics animation <%= key.parameterize[0..2] %> p-4">
          <h3>
            <i class="fas fa-microphone"></i>
            <span>
              <%= l(schedule_item.hour, format: :hour_short) %>
            </span>
            <%= schedule_item.name %>
          </h3>
        </div>
      <% end %>
    <% end %>
  </div>  

app/views/home/content/_slides.html.erb
 <!-- Promotions -->
<div class="row mt-2 mb-4 d-flex flex-column flex-sm-row">
  <div class="col col-md-8 rounded pr-sm-0 mb-2 mb-sm-0">
  
  <% if @promotions.present? %>
    <div id="carousel-destaque" class="carousel slide carousel-fade z-depth-1-half rounded" data-ride="carousel">
      <ol class="carousel-indicators">
        <% @promotions.each_with_index do |promotion, index| %>
          <li data-target="#carousel-destaque" data-slide-to="<%= index %>"
          class="<%= 'active' if index == 0 %>"></li>
        <% end %>     
      </ol>
      <div class="carousel-inner rounded" role="listbox">
        <% @promotions.each_with_index do |promotion, index| %>
          <div class="carousel-item <%= 'active' if index == 0 %>">
            <div class="view">
                <%= image_tag promotion.image.url, class: "d-block w-100" %>             
              <div class="mask rgba-black-light"></div>
            </div>
            <div class="carousel-caption carousel-styled-caption">
              <h5 class=""><%= promotion.title%></h5>
              <%= link_to promotion_path(promotion.slug), class: "btn bg-primary btn-rounded"  do %>
                <p class="text-white m-0">Clique aqui e saiba como participar</p>             
              <% end %>              
            </div>
          </div>
        <%end%>      
      </div>
      <a class="carousel-control-prev" href="#carousel-destaque" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-destaque" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>    
  <% else %>   
   <div class="carousel-inner rounded" role="listbox">    
      <div class="carousel-item active">
        <div class="view">
            <%= image_tag 'promocoes.png', class: "d-block w-100" %>             
          <div class="mask rgba-black-light"></div>
        </div>         
      </div>       
    </div> 
  <% end %>
  
  </div>
  <!-- Videos -->
  <div class="col col-md-4 d-flex flex-column justify-content-between">
    <div id="carousel-destaque-sm-1" class="carousel slide carousel-fade z-depth-1-half rounded mb-2 mb-sm-0" data-ride="carousel">
      <ol class="carousel-indicators">
         <% @videos.each_with_index do |video, index| %>
          <li data-target="#carousel-destaque-sm-1" data-slide-to="<%= index %>"
          class="<%= 'active' if index == 0 %>"></li>
         <% end %>
      </ol>
      <div class="carousel-inner rounded" role="listbox">
        <% @videos.each_with_index do |video, index| %>
          <div class="carousel-item <%= 'active' if index == 0 %>">
            <div class="view">              
              <%= image_tag video.image, class: "d-block w-100" %>             
              <div class="mask rgba-black-light"></div>
            </div>
            <div class="carousel-caption carousel-styled-caption">
              <h5 class=""><%= video.title%></h5>
               <%= link_to video_path(video), class: "btn bg-primary btn-rounded" do %>
                  <p class="text-white m-0">Ver o vídeo</p>             
                <% end %>
            </div>
          </div>
        <% end %>      
      </div>  
      <a class="carousel-control-prev" href="#carousel-destaque-sm-1" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-destaque-sm-1" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

   <!-- Photos -->
    <div id="carousel-destaque-sm-2" class="carousel slide carousel-fade z-depth-1-half rounded" data-ride="carousel">
      <ol class="carousel-indicators">
        <% @albums.each_with_index do |album, index| %>
        <li data-target="#carousel-destaque-sm-2" data-slide-to="<%= index %>"
        class="<%= 'active' if index == 0 %>"></li>
        <% end %>      
      </ol>
      <div class="carousel-inner rounded" role="listbox">
       <% @albums.each_with_index do |album, index| %>
          <div class="carousel-item <%= 'active' if index == 0 %>">
            <div class="view"> 
              <% if album.image.present? %>
                  <%= image_tag album.image , class: "d-block w-100" %> 
              <% else %>
                <%= image_tag 'logo.png', class: "d-block w-100"%>
              <% end %>                          
              <div class="mask rgba-black-light"></div>
            </div>
            <div class="carousel-caption carousel-styled-caption">
              <h5 class=""><%= album.name%></h5>
               <%= link_to album_path(album), class: "btn bg-primary btn-rounded" do %>
                  <p class="text-white m-0">Ver as fotos</p>             
                <% end %>
            </div>
          </div>
        <% end %>          
      </div>

      <a class="carousel-control-prev" href="#carousel-destaque-sm-2" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-destaque-sm-2" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>